version: '3.5'

services:
  koa2-basic-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    command:
      - "npm"
      - "run"
      - "watch"
    env_file:
      - src/conf/development
      - src/conf/development.secret
    ports:
      - 4000:4000
      - 9229:9229
    depends_on:
      - mysql
    volumes:
      - ".:/usr/app"
  mysql:
    image: mysql
    container_name: my-app-sql
    env_file:
      - src/conf/development
      - src/conf/development.secret
    ports:
      - 3306:3306
    volumes:
      - my-app-sql:/var/lib/mysql

volumes:
  my-app-sql:

